/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.0/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.guava:guava:33.0.0-jre")
    implementation("de.articdive:jnoise-pipeline:4.1.0")
    implementation("de.articdive:jnoise-modifiers:4.1.0")
    implementation("dev.dominion.ecs:dominion-ecs-api:0.9.0")
    implementation("dev.dominion.ecs:dominion-ecs-engine:0.9.0")
    implementation("org.openjdk.jmh:jmh-core:1.37")
    annotationProcessor("org.openjdk.jmh:jmh-generator-annprocess:1.37")
}

val jmh by tasks.registering(JavaExec::class) {
    group = "benchmark"
    description = "Runs JMH benchmarks from the main source set."
    dependsOn(tasks.named("classes"))
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "org.openjdk.jmh.Main"
    val reportDir = layout.buildDirectory.dir("reports/jmh")
    val reportFile = reportDir.map { it.file("results.txt").asFile.absolutePath }
    outputs.dir(reportDir)
    jvmArgs("-XX:+UnlockDiagnosticVMOptions", "-XX:+PrintInlining")
    args("-rf", "text", "-rff", reportFile.get())
}

val jmhFfmWithWrapperInlining by tasks.registering(JavaExec::class) {
    group = "benchmark"
    description = "Runs only ffmWithWrapper and prints inlining decisions for that method."
    dependsOn(tasks.named("classes"))
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "org.openjdk.jmh.Main"
    val reportDir = layout.buildDirectory.dir("reports/jmh")
    val reportFile = reportDir.map { it.file("ffmWithWrapper-inlining.txt").asFile.absolutePath }
    outputs.dir(reportDir)
    jvmArgs(
        "-XX:+UnlockDiagnosticVMOptions",
        "-XX:CompileCommand=option,br/com/pietroth/tsa/DecoderBenchmark.ffmWithWrapper,PrintInlining"
    )
    args(
        "DecoderBenchmark.ffmWithWrapper",
        "-rf", "text",
        "-rff", reportFile.get()
    )
}

val jmhIntentionLayouts by tasks.registering(JavaExec::class) {
    group = "benchmark"
    description = "Runs the SOA vs AOS dispatch-table benchmark and saves the results to a file."
    dependsOn(tasks.named("classes"))
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "org.openjdk.jmh.Main"
    val reportDir = layout.buildDirectory.dir("reports/jmh")
    val reportFile = reportDir.map { it.file("intention-dispatch-layouts.txt").asFile.absolutePath }
    outputs.dir(reportDir)
    args(
        "IntentionLayoutBenchmark.dispatchAos",
        "IntentionLayoutBenchmark.dispatchSoa",
        "-rf", "text",
        "-rff", reportFile.get()
    )
}

tasks.withType<JavaExec> {
    standardInput = System.`in`
}

tasks.withType<JavaCompile>().configureEach {
    // options.compilerArgs.add("--enable-preview") // Just for Java 21
}

tasks.withType<JavaExec>().configureEach {
    jvmArgs("--enable-native-access=ALL-UNNAMED")
}


testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit4 test framework
            useJUnit("4.13.2")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    // Define the main class for the application.
    mainClass = "br.com.pietroth.tsa.App"
}
