/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.0/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.guava:guava:33.0.0-jre")
    implementation("de.articdive:jnoise-pipeline:4.1.0")
    implementation("de.articdive:jnoise-modifiers:4.1.0")
    implementation("dev.dominion.ecs:dominion-ecs-api:0.9.0")
    implementation("dev.dominion.ecs:dominion-ecs-engine:0.9.0")
}

tasks.withType<JavaExec> {
    standardInput = System.`in`
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit4 test framework
            useJUnit("4.13.2")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}

application {
    // Define the main class for the application.
    mainClass = "br.com.pietroth.tsa.App"
}
